$:.unshift(File.dirname(__FILE__) + '/../../example_rails_app/vendor/plugins/rspec/lib')
require 'rubygems'
require 'spec/rake/spectask'

task :default => :spec

desc "Run all specs"
Spec::Rake::SpecTask.new do |t|
  t.rcov = true
  t.spec_opts = ['--colour', '--diff']
  t.rcov_opts = ['--exclude', 'rspec\/plugins,rspec\/lib\/spec,spec\/spec,fixtures,bin\/spec']
end
